x="hello"
print(x)
print(type(x))
print(len(x))
y="python is a programming, language"
print(y)
print(len(y))
print("is" in y)
print("are" in y)
print("is" not in y)
print("are" not in y)
for i in y:
    print(i)
print(y[1])
print(y[6])
print(y[3:12])
print(y[10:])
print(y[:15])
print(y[-1])
print(y[-10:-3])
print(y.upper())
print(y.lower())
x="   ernakulam is a developed district  "
print(x)
print(x.strip())
print(y.replace("python","java"))
print(y.split(","))
print(y+x)
z=8
#print(z+x)
print(f"i am {z} years old")
print(y.count("a"))
